export { default as TextLogo } from './TextLogo'
export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as StaticPage } from './StaticPage'
export { default as SplashScreen } from './SplashScreen'
